version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 382001a
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data